### ISSUE TITLE
about seg_mask generation

### ISSUE THREAD

**Issue by mengmeng0406** [hu64/SpotNet#11]
Hi, could you please share your files in csv format? i.e. '/store/datasets/UAV/csv.csv' or '/store/datasets/UAV/val.csv' or sharing some code elaborating how the files in csv  format are being created? Thanks.

**Comment by hu64** [comment]
Hi, I just added my csv files as well as the scripts I used to convert the dataset format to the csv format to: https://polymtlca0-my.sharepoint.com/:f:/g/personal/hughes_perreault_polymtl_ca/EhqSkfDIJ-JBh9_YhCrPQrEBocvfP6BIucODKdcNjZzlcA?e=xqRuEv

The csv files are quite simple, the format is: path, x0, y0, x1, y1, label. In the scripts you can also find the sequences I used for val / train split.

**Comment by mengmeng0406** [comment]
Thanks for your reply!

**Comment by mengmeng0406** [comment]
I used the file "generate.py" to generate a optical flow image, and the file "flow_to_seg_bbox.py" to make segmentation labels. However, the label is not as credible as in the paper. Did you use other processes to generate optical flow images?

**Comment by mengmeng0406** [comment]
[mask_generation.txt](https://github.com/hu64/SpotNet/files/6187555/mask_generation.txt)
Here is my code.

**Comment by mengmeng0406** [comment]
![img000001](https://user-images.githubusercontent.com/57563422/112107625-2720c800-8bea-11eb-9383-8403e0a1dbdb.jpg)
![label_img000001](https://user-images.githubusercontent.com/57563422/112107638-2daf3f80-8bea-11eb-840b-aaa2be4b26d4.jpg)
Here are example of segmentation label and its original image

**Comment by mengmeng0406** [comment]
I found where the code was wrong, sorry to disturb
