### ISSUE TITLE
Code of converting UA DETRAC into COCO format

### ISSUE THREAD

**Issue by lizhaoliu-Lec** [hu64/SpotNet#15]
Thanks for your great work! Would it be convenient for you to share the code of converting UA DETRAC into COCO format?

**Comment by hu64** [comment]
Hi, I use "https://github.com/hu64/SpotNet/blob/master/object%20detection/src/tools/convert_csv_to_coco.py". The csv files are converted from the UA-DETRAC xml and the format is filepath, x0, y0, x1, y1, label.

**Comment by lizhaoliu-Lec** [comment]
Many thanks! But I have already finished the converting scripts.  For more details, see https://github.com/lizhaoliu-Lec/UA-DETRAC-Preprocess.
