### ISSUE TITLE
Do you multiply  the width&height and offset(x) offset(y) feature maps with the segmentation map?

### ISSUE THREAD

**Issue by sisrfeng** [hu64/SpotNet#3]
> To attenuate the response at locations unlikely to contain an object of interest, we multiply every channel of the feature map with our segmentation map, thus reducing the probability of false positives in irrelevant areas.

If the with&height  featrue maps are multiplied with the  segmentation map, the size will be smaller, right?
thx!

**Comment by hu64** [comment]
Hi, no indeed we do not multiply the width&height nor the offset maps with our attention maps, since intuitively I could not see how that would make sense for these values. Yeah the size would be smaller I think, that's logical.

**Comment by sisrfeng** [comment]
Is using heatmap instead of feature map in the paper more accurate ? width&height nor the offset maps are also feature map, I think.

**Comment by hu64** [comment]
Yes you are right, that would be more accurate!

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/89102465-0da0f500-d43c-11ea-9041-e1eb4e90a2bf.png)
![image](https://user-images.githubusercontent.com/53520949/89102473-1abde400-d43c-11ea-8ab6-96f76e4e1244.png)

But according to your slides, you multiply the segmentation map with feature maps used by the heat map branch, rather than multiply the segmentation map with the heat map 

the heat map  branch consists of some conv layers:
![image](https://user-images.githubusercontent.com/53520949/89102486-450fa180-d43c-11ea-9cca-8f629fa93c1c.png
I am a little confused now.

**Comment by sisrfeng** [comment]
BTW, are attention map and segmentation map the same thing in your paper and slides?

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/89102873-c1f04a80-d43f-11ea-9660-39da6efa8ade.png)
Is the value of the  foreground/background segmentation map binaried（0 or 1 ） or  in  [0,1] interval?
I think the word **_foreground/background segmentation_**  implies pixel-wise 2 classes classification (0 or 1) and attention map sounds like ∈[0,1].  And attention heat map may be more clear than attention map. 
Thx!

**Comment by hu64** [comment]
The attention map is a learned foreground/background segmentation, so the value is a probability of being 1 or zero. We can binarize it or not to our convenience. So yes they reference the same thing. And actually it's a mistake in the slides, we only apply the attention on the heatmap branch.
