### ISSUE TITLE
what is the FPS of the network? Have you tried DLA and resdcn?

### ISSUE THREAD

**Issue by sisrfeng** [hu64/SpotNet#5]
> We used the stacked hourglass network as our backbone because it shows the best performance for keypoint estimation. 

It get high mAP but low FPS, right?

**Comment by hu64** [comment]
I think it's around 15fps for my GTX 1080 Ti. I did not try these other networks.

**Comment by sisrfeng** [comment]
The ua-detrac challenge does not care about FPS, so you just want high AP?

**Comment by hu64** [comment]
Yes exactly, for this work the main goal was performance.

**Comment by sisrfeng** [comment]
I think the word performance is not as clear as high AP here, because performance may include AP and FPS  :)
Thx!
