### ISSUE TITLE
Do these two statments about the segmentation head conflit with each other?

### ISSUE THREAD

**Issue by sisrfeng** [hu64/SpotNet#6]
![image](https://user-images.githubusercontent.com/53520949/89102996-03cdc080-d441-11ea-82dd-97328a32cf29.png)
Segmentation Head: each block is composed of two 
3x3 convolutions followed by upsampling

The added segmentation head takes as input a feature map
that has been reduced by a factor of four in terms of spatial
dimension when compared to the input. It consists of three
3 × 3 convolutions, with upsampling layers in between. 

Do these two statments conflit with each other?

**Comment by hu64** [comment]
We tested several small networks for this and found the performance is not super sensitive to which small network is used, we even tried U-Nets. In the end we kept three 3x3 convolutions followed by upsampling.
