### ISSUE TITLE
How do you handle the ignore region in the dataset? I have not found relevant code in this repo.

### ISSUE THREAD

**Issue by sisrfeng** [hu64/SpotNet#8]
I trained centerNet on UA-detrac, without considering the ignore region. The trained model can not find small vehicle. 
So I think the ignore region is important.

Thx!

**Comment by hu64** [comment]
Hi! Personally, I don't consider the ignore region during training. I know that it probably penalizes the network for some incorrect "false positives", real detected vehicles that are not in the ground-truth, but I think the impact should be minimal. If you try it, let me know if it improves the performance!

**Comment by sisrfeng** [comment]
Thx !
On UA-detrac training+ testing set, my classmate trains centerNet, which has been trained by the author on coco,  and it performs worse than before on small object obviously.  I think the impact is important.
I' ll consider the ignore region and share my results with you.

**Comment by sisrfeng** [comment]
The code of handling the ignore region can be reffered  from  (an ECCV paper' s work): 
https://github.com/shijieS/DMMN/blob/d9ef345f1cb9367aea36fe46d3299ee1f8677e3b/dataset/ua/ua_reader_backup.py#L111
